"""
--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it.
You aren't sure how old it is, or whether it can even support your weight.
It seems to support the Elves just fine, though.
The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist.
You decide to distract yourself by modeling rope physics;
maybe you can even figure out where not to step.

Consider a rope with a knot at each end;
these knots mark the head and the tail of the rope.
If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths,
you should be able to model the positions of the knots on a two-dimensional grid.
Then, by following a hypothetical series of motions (your puzzle input)
 for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short;
in fact, the head (H) and tail (T) must always be touching
(diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
If the head is ever two steps directly up, down, left, or right from the tail,
the tail must also move one step in that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
Otherwise, if the head and tail aren't touching and aren't in the same row or column,
the tail always moves one step diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
You just need to work out where the tail goes as the head follows a series of motions.
Assume the head and the tail both start at the same position, overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2
This series of motions moves the head right four steps,
then up four steps, then left three steps, then down one step, and so on.
After each step, you'll need to update the position of the tail
if the step means the head is no longer adjacent to the tail.
Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
After simulating the rope,
you can count up all of the positions the tail visited at least once.
In this diagram, s again marks the starting position (which the tail also visited)
and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..
So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions.
How many positions does the tail of the rope visit at least once?
"""
from dataclasses import dataclass
from enum import Enum


def sign(number: int):
    if number == 0:
        return 0
    elif number > 0:
        return 1
    else:
        return -1


@dataclass(eq=True, frozen=True)
class Knot:
    x: int
    y: int

    def __add__(self, other):
        return Knot(self.x + other.x, self.y + other.y)


class Direction(Enum):
    LEFT = Knot(-1, 0)
    RIGHT = Knot(1, 0)
    UP = Knot(0, 1)
    DOWN = Knot(0, -1)


class Rope:
    def __init__(self, knot_count: int):
        self.knots = [Knot(0, 0)] * knot_count
        self.tail_history = []

    def move(self, direction: Direction):
        self.knots[0] += direction.value
        for index in range(1, len(self.knots)):
            horizontal_difference = self.knots[index - 1].x - self.knots[index].x
            vertical_difference = self.knots[index - 1].y - self.knots[index].y
            if abs(horizontal_difference) > 1 or abs(vertical_difference) > 1:
                self.knots[index] += Knot(sign(horizontal_difference), sign(vertical_difference))
            self.tail_history.append(self.knots[-1])


@dataclass
class PlanckMovement:
    direction: Direction
    multiplier: int


def read_data_file(input_file_path: str) -> list[str]:
    with open(input_file_path) as f:
        lines = f.read().splitlines()
    return lines


def process_data_to_planck_rope_movement(raw_data_lines):
    planck_movement_list = []
    direction_dictionary = {
        "L": Direction.LEFT,
        "R": Direction.RIGHT,
        "U": Direction.UP,
        "D": Direction.DOWN
    }
    for line in raw_data_lines:
        raw_direction, raw_multiplier = line.split()
        planck_movement_list.append(PlanckMovement(
            direction_dictionary[raw_direction],
            int(raw_multiplier)
        ))
    return planck_movement_list


if __name__ == '__main__':
    """
    for test input answer should be 13 and rope length 2
    for real input answer should be 1675 and rope length 2
    for test input answer should be 1 and rope length 10
    for real input answer should be 2578 and rope length 10
    """
    raw_data = read_data_file("puzzle_input.txt")
    movements = process_data_to_planck_rope_movement(raw_data)
    rope = Rope(2)
    for movement in movements:
        for _ in range(movement.multiplier):
            rope.move(movement.direction)
    print(len(set(rope.tail_history)))
